switch base test environment to 3.11, bump minimum cython version to account for 3.11 changes, use cibuildwheel for wheel creation

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,8 +12,8 @@ jobs:
 
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-        python-version: [3.7, 3.8, 3.9]
+        python-version: [3.11]
+        os: [ubuntu-20.04, windows-2022, macos-11]
 
     steps:
     - uses: actions/checkout@v3
@@ -37,8 +37,21 @@ jobs:
 
     - name: Package and check
       run: |
-        python setup.py sdist bdist_wheel
+        python setup.py sdist
         python -m twine check dist/*
+
+    - name: Install cibuildwheel
+      run: python -m pip install cibuildwheel==2.11.2
+
+    - name: Build wheels
+      run: python -m cibuildwheel --output-dir wheelhouse
+      env:
+        CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-* cp311-*"
+        CIBW_SKIP: "*-musllinux_i686"
+
+    - uses: actions/upload-artifact@v3
+      with:
+        path: ./wheelhouse/*.whl
 
     - name: Publish distribution 📦 to PyPI
       if: ${{ startsWith(github.ref, 'refs/tags') && matrix.os != 'ubuntu-latest' }}
@@ -46,6 +59,6 @@ jobs:
         TWINE_USERNAME: ${{ secrets.PYPI_UN }}
         TWINE_PASSWORD: ${{ secrets.PYPI_PW }}
       run: |
-        python -m twine upload dist/* --skip-existing || echo "Failed to deploy"
+        python -m twine upload dist/* wheelhouse/* --skip-existing || echo "Failed to deploy"
 
 
